import { NextResponse } from 'next/server'
import nodemailer from 'nodemailer'

function buildEmailHtml(data: Record<string, unknown>): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #04070F; color: #F8FAFC; margin: 0; padding: 0; }
    .wrapper { max-width: 600px; margin: 0 auto; padding: 40px 24px; }
    .header { background: linear-gradient(135deg, #00D4FF, #8B5CF6); padding: 2px; border-radius: 16px; margin-bottom: 32px; }
    .header-inner { background: #080D1A; border-radius: 14px; padding: 28px 32px; }
    .logo { font-size: 22px; font-weight: 700; letter-spacing: -0.02em; color: #F8FAFC; }
    .logo span { background: linear-gradient(135deg, #00D4FF, #8B5CF6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    .badge { display: inline-block; background: rgba(0,212,255,0.12); border: 1px solid rgba(0,212,255,0.25); color: #00D4FF; font-size: 11px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; padding: 4px 12px; border-radius: 99px; margin-top: 8px; }
    .card { background: #080D1A; border: 1px solid #1E293B; border-radius: 12px; padding: 24px; margin-bottom: 16px; }
    .section-label { font-size: 11px; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; color: #475569; margin-bottom: 16px; }
    .field { display: flex; justify-content: space-between; align-items: flex-start; padding: 10px 0; border-bottom: 1px solid #1E293B; }
    .field:last-child { border-bottom: none; }
    .field-label { font-size: 13px; color: #94A3B8; min-width: 140px; }
    .field-value { font-size: 13px; color: #F8FAFC; font-weight: 500; text-align: right; max-width: 300px; }
    .slot-card { background: linear-gradient(135deg, rgba(0,212,255,0.08), rgba(139,92,246,0.08)); border: 1px solid rgba(0,212,255,0.2); border-radius: 10px; padding: 16px 20px; margin-bottom: 16px; }
    .slot-time { font-size: 18px; font-weight: 700; color: #00D4FF; }
    .slot-meta { font-size: 12px; color: #94A3B8; margin-top: 4px; }
    .message-box { background: #0D1426; border: 1px solid #1E293B; border-radius: 8px; padding: 16px; font-size: 13px; color: #94A3B8; line-height: 1.6; margin-top: 8px; }
    .footer { text-align: center; margin-top: 32px; font-size: 12px; color: #475569; }
    .cta { display: inline-block; background: linear-gradient(135deg, #00D4FF, #8B5CF6); color: #04070F; font-weight: 700; font-size: 14px; padding: 12px 28px; border-radius: 8px; text-decoration: none; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <div class="header-inner">
        <div class="logo">Azentyk<span>.AI</span></div>
        <div class="badge">New Demo Request</div>
      </div>
    </div>

    ${data.preferredSlot ? `
    <div class="card">
      <div class="section-label">Preferred Demo Slot</div>
      <div class="slot-card">
        <div class="slot-time">${data.preferredSlot}</div>
        <div class="slot-meta">30 min · Video Call · India Standard Time</div>
      </div>
    </div>
    ` : ''}

    <div class="card">
      <div class="section-label">Contact Details</div>
      <div class="field">
        <span class="field-label">Full Name</span>
        <span class="field-value">${data.fullName}</span>
      </div>
      <div class="field">
        <span class="field-label">Work Email</span>
        <span class="field-value">${data.email}</span>
      </div>
      <div class="field">
        <span class="field-label">Organisation</span>
        <span class="field-value">${data.company}</span>
      </div>
      <div class="field">
        <span class="field-label">Role</span>
        <span class="field-value">${data.role}</span>
      </div>
      <div class="field">
        <span class="field-label">Patient Visits/Month</span>
        <span class="field-value">${data.visits}</span>
      </div>
      <div class="field">
        <span class="field-label">Use Cases</span>
        <span class="field-value">${(data.useCases as string[]).join(', ')}</span>
      </div>
    </div>

    ${data.message ? `
    <div class="card">
      <div class="section-label">Message</div>
      <div class="message-box">${data.message}</div>
    </div>
    ` : ''}

    <div style="text-align:center;">
      <a href="mailto:${data.email}" class="cta">Reply to ${(data.fullName as string).split(' ')[0]}</a>
    </div>

    <div class="footer">
      Azentyk.AI · contact@azentyk.ai · Dallas, TX<br/>
      This email was generated by the Azentyk website contact form.
    </div>
  </div>
</body>
</html>
  `.trim()
}

export async function POST(request: Request) {
  try {
    const data = await request.json()

    if (!data.fullName || !data.email || !data.company) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 422 })
    }

    const isSmtpConfigured =
      process.env.SMTP_HOST &&
      process.env.SMTP_USER &&
      process.env.SMTP_PASSWORD

    if (isSmtpConfigured) {
      const port = Number(process.env.SMTP_PORT) || 587
      const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port,
        secure: port === 465,
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASSWORD,
        },
      })

      await transporter.sendMail({
        from: `"Azentyk.AI Website" <${process.env.SMTP_FROM || process.env.SMTP_USER}>`,
        to: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'contact@azentyk.ai',
        replyTo: data.email as string,
        subject: `Demo Request — ${data.fullName} at ${data.company}${data.preferredSlot ? ` · ${data.preferredSlot}` : ''}`,
        html: buildEmailHtml(data),
      })
    } else {
      console.log('[Azentyk] SMTP not configured — simulating send:', {
        name: data.fullName,
        email: data.email,
        company: data.company,
        slot: data.preferredSlot,
      })
    }

    return NextResponse.json({ success: true }, { status: 200 })
  } catch (error) {
    console.error('[Azentyk] Contact form error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
